# Generated by Django 3.2.3 on 2021-05-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('id_mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hack.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_status', models.BooleanField(default=True)),
                ('comment_team', models.TextField(blank=True, null=True)),
                ('comment_mentor', models.TextField(blank=True, null=True)),
                ('mentor_assessment', models.CharField(blank=True, max_length=100, null=True)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hack.session')),
                ('id_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hack.team')),
            ],
        ),
    ]
